### ISSUE TITLE
How to disable SmartLook on specified private pages

### ISSUE THREAD

**Issue by mlatal** [s3rgiosan/wpsmartlook#1]
Is possible to implement checkbox for disable SmartLook code on specified private pages? For example create checkbox on page editation for disable recording. Or is there another way how to filter pages out from recording? Thx for answer.

**Comment by krsiakdaniel** [comment]
Hi @mlatal ... switch to official plugin for Smartlook:
https://wordpress.org/plugins/smartlook-visitor-screen-recording/

We plan similar future in the future so you will get update in future version.

Cheers mate

**Daniel**
Smartlook team
http://www.getsmartlook.com/

**Comment by s3rgiosan** [comment]
Hi @mlatal,

First of all sorry for the late reply. Second of all, the feature you suggested is going to be available on the next release. Sometime during the day.

Thanks for the suggestion!

Regards

**Comment by s3rgiosan** [comment]
Hi @mlatal,

The version [1.1.0](https://github.com/s3rgiosan/wpsmartlook/releases/tag/1.1.0) adds the ability to disable recording for specific content types. 

On each edit page you'll find a "Settings" metabox with a checkbox for disabling the snippet inclusion for that content.

Best regards
